

# SSH登陆虚拟机
Administrator@Hasee-PC MINGW64 /f/packages/20191026/terrace/automatic (master)
$ vagrant ssh
Last login: Sun Oct 27 04:46:08 2019 from 10.0.2.2


进入开发环境 
Administrator@Hasee-PC MINGW64 /f/packages/20191026
$ source venv/bin/activate
(venv)



启动、退出虚拟环境



Administrator@Hasee-PC MINGW64 /f/packages/20191026/terrace/automatic (master)
$ python3 manage.py qmonitor
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "D:\lib\site-packages\django-2.0.5-py3.6.egg\django\core\management\__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "D:\lib\site-packages\django-2.0.5-py3.6.egg\django\core\management\__init__.py", line 347, in execute
    django.setup()
  File "D:\lib\site-packages\django-2.0.5-py3.6.egg\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "D:\lib\site-packages\django-2.0.5-py3.6.egg\django\apps\registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "D:\lib\site-packages\django-2.0.5-py3.6.egg\django\apps\config.py", line 90, in create
    module = import_module(entry)
  File "D:\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django_celery_results'
(venv)





Administrator@Hasee-PC MINGW64 /f/packages/20191026/terrace/automatic (master)
$  python3 manage.py qcluster
(0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
(0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
(0.000) SELECT VERSION(); args=None
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "D:\lib\site-packages\django-2.0.5-py3.6.egg\django\core\management\__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "D:\lib\site-packages\django-2.0.5-py3.6.egg\django\core\management\__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "D:\lib\site-packages\django-2.0.5-py3.6.egg\django\core\management\base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "D:\lib\site-packages\django-2.0.5-py3.6.egg\django\core\management\base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "D:\lib\site-packages\django_q\management\commands\qcluster.py", line 22, in handle
    q.start()
  File "D:\lib\site-packages\django_q\cluster.py", line 53, in start
    self.sentinel.start()
  File "D:\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "D:\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle _thread.lock objects
(venv)
Administrator@Hasee-PC MINGW64 /f/packages/20191026/terrace/automatic (master)
$ Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\lib\multiprocessing\spawn.py", line 99, in spawn_main
    new_handle = reduction.steal_handle(parent_pid, pipe_handle)
  File "D:\lib\multiprocessing\reduction.py", line 87, in steal_handle
    _winapi.DUPLICATE_SAME_ACCESS | _winapi.DUPLICATE_CLOSE_SOURCE)
PermissionError: [WinError 5] ▒ܾ▒▒▒▒ʡ▒




Administrator@Hasee-PC MINGW64 /f/packages/20191026/terrace/automatic (master)
$ python3 manage.py runserver 192.168.1.100:8006



